version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      midnight-sdk:
        patterns:
          - '@midnight-ntwrk/*'
          - '@midnightntwrk/*'
    open-pull-requests-limit: 10

  - package-ecosystem: 'docker'
    directory: '/packages/server'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/packages/client'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
