// Thin simulator around the compiled ballot contract, following the
// confirmed real pattern for testing generated Compact contracts:
// createConstructorContext/createCircuitContext + Contract.initialState +
// Contract.impureCircuits.<name>(context, ...args) threading the returned
// CircuitContext through each subsequent call. See docs/DECISIONS.md
// "Verified directly from installed npm packages" for sources.
import {
  createCircuitContext,
  createConstructorContext,
  emptyZswapLocalState,
  sampleContractAddress,
  type CircuitContext,
  type MerkleTreePath
} from '@midnight-ntwrk/compact-runtime';
// Generated by `npm run compile:contracts` — see managed/README.md.
// eslint-disable-next-line import/no-unresolved
import { Contract, ledger, pureCircuits, Phase, type Ledger } from '../managed/ballot/contract/index.cjs';
import { ballotWitnesses, createBallotPrivateState, type BallotPrivateState } from '../src/witnesses.js';

const SAMPLE_COIN_PUBLIC_KEY = { bytes: new Uint8Array(32).fill(7) };

export { Phase };
export { pureCircuits };

export class BallotSimulator {
  private readonly contract = new Contract<BallotPrivateState>(ballotWitnesses);
  private context: CircuitContext<BallotPrivateState>;

  constructor(
    organizerSecretKey: Uint8Array,
    pollIdSeed: Uint8Array,
    initialOptionCount: bigint
  ) {
    const organizerKeyCommitment = pureCircuits.organizerKeyFor(organizerSecretKey);
    const constructorContext = createConstructorContext(
      createBallotPrivateState(organizerSecretKey),
      SAMPLE_COIN_PUBLIC_KEY
    );
    const deployed = this.contract.initialState(
      constructorContext,
      organizerKeyCommitment,
      pollIdSeed,
      initialOptionCount
    );
    this.context = createCircuitContext(
      'constructor',
      sampleContractAddress(),
      emptyZswapLocalState(SAMPLE_COIN_PUBLIC_KEY),
      deployed.currentContractState,
      deployed.currentPrivateState
    );
  }

  /**
   * Swaps in a different caller's secret key for the next circuit call, by
   * rebuilding the circuit context from the current on-chain state with a
   * fresh private state — mirroring a different wallet (with a different
   * local secret) submitting the next transaction against the same chain.
   */
  asCaller(secretKey: Uint8Array): this {
    const address = this.context.callContext.contractAddress;
    this.context = createCircuitContext(
      'call',
      address,
      this.context.zswapLocalStates[address] ?? emptyZswapLocalState(SAMPLE_COIN_PUBLIC_KEY),
      this.context.callContext.currentQueryContext.state,
      createBallotPrivateState(secretKey)
    );
    return this;
  }

  registerVoter(commitment: Uint8Array): void {
    const { context } = this.contract.impureCircuits.registerVoter(this.context, commitment);
    this.context = context;
  }

  openVoting(): void {
    const { context } = this.contract.impureCircuits.openVoting(this.context);
    this.context = context;
  }

  closeVoting(): void {
    const { context } = this.contract.impureCircuits.closeVoting(this.context);
    this.context = context;
  }

  castVote(option: bigint, path: MerkleTreePath<Uint8Array>): void {
    const { context } = this.contract.impureCircuits.castVote(this.context, option, path);
    this.context = context;
  }

  get ledger(): Ledger {
    return ledger(this.context.callContext.currentQueryContext.state);
  }
}
