// Witness implementations for ballot.compact. Runs ONLY inside the caller's
// own process (browser wallet or an organizer's local CLI run) — never on
// the server. See docs/WALLET_INTEGRATION.md and docs/THREAT_MODEL.md.
//
// `Ledger` is generated by `compactc` into managed/ballot/contract — see
// managed/README.md for how to (re)generate it. This import only resolves
// after `npm run compile:contracts` has run once.
import type { WitnessContext } from '@midnight-ntwrk/compact-runtime';
// eslint-disable-next-line import/no-unresolved -- generated at compile time, see managed/README.md
import type { Ledger } from '../managed/ballot/contract/index.cjs';

/**
 * Local private state for a ballot.compact caller. A single caller is
 * either "the organizer" (only ever invokes registerVoter/openVoting/
 * closeVoting, which read `organizerSecretKey`) or "a voter" (only ever
 * invokes castVote, which reads `voterSecret`) — both witnesses read the
 * same local secret because only one of them is ever exercised per role.
 * Never persisted anywhere but the caller's own encrypted local storage
 * (see the private state provider in packages/shared/src/providers.ts).
 */
export interface BallotPrivateState {
  readonly secretKey: Uint8Array;
}

export const createBallotPrivateState = (secretKey: Uint8Array): BallotPrivateState => ({
  secretKey
});

export const ballotWitnesses = {
  voterSecret(
    context: WitnessContext<Ledger, BallotPrivateState>
  ): [BallotPrivateState, Uint8Array] {
    return [context.privateState, context.privateState.secretKey];
  },
  organizerSecretKey(
    context: WitnessContext<Ledger, BallotPrivateState>
  ): [BallotPrivateState, Uint8Array] {
    return [context.privateState, context.privateState.secretKey];
  }
};
